
#ifndef __PACKET_ENUMERATIONS_H
#define __PACKET_ENUMERATIONS_H

enum
{
	// TODO: PacketEnumerations.h is not complete yet

	/*
		Notes:
		- Apperently there are two ID_NEW_INCOMING_CONNECTION. 24 and 30
		  It is certain that ID 30 is the real ID_NEW_INCOMING_CONNECTION, because
		  RakNet uses this ID for ReplicaManager::OnReceive, ConnectionGraph::OnReceive, etc...
		  Packet ID 24 only used in CNetGame::Process so far. Maybe there are auth packets between these IDs?
	*/

	ID_UNK_12_SYNC = 12, // TODO: ID_UNK_12_SYNC

	ID_NEW_INCOMING_CONNECTION_2 = 24,

	ID_CONNECTION_ATTEMPT_FAILED = 29,
	ID_NEW_INCOMING_CONNECTION = 30,
	ID_NO_FREE_INCOMING_CONNECTIONS = 31,
	ID_DISCONNECTION_NOTIFICATION = 32,
	ID_CONNECTION_LOST = 33,
	ID_CONNECTION_REQUEST_ACCEPTED = 34,
	ID_RSA_PUBLIC_KEY_MISMATCH = 35,
	ID_CONNECTION_BANNED = 36,
	ID_INVALID_PASSWORD = 37,
	ID_MODIFIED_PACKET = 38,

	ID_TIMESTAMP = 40,

	ID_REMOTE_DISCONNECTION_NOTIFICATION = 42,
	ID_REMOTE_CONNECTION_LOST = 43,

	ID_CONNECTION_GRAPH_REQUEST = 57,
	ID_CONNECTION_GRAPH_REPLY = 58,
	ID_CONNECTION_GRAPH_UPDATE = 59,
	ID_CONNECTION_GRAPH_NEW_CONNECTION = 60,

	ID_CONNECTION_GRAPH_CONNECTION_LOST = 61,
	ID_CONNECTION_GRAPH_DISCONNECTION_NOTIFICATION = 62,

	ID_REPLICA_MANAGER_CONSTRUCTION = 63,
	ID_REPLICA_MANAGER_DESTRUCTION = 64,
	ID_REPLICA_MANAGER_SCOPE_CHANGE = 65,
	ID_REPLICA_MANAGER_SERIALIZE = 66,
	ID_REPLICA_MANAGER_DOWNLOAD_COMPLETE = 67,

	// SA-MP
	// Found in L: 08067810 - Thanks Kalcor!
	ID_VEHICLE_SYNC = 200,
	ID_RCON_COMMAND = 201,
	ID_RCON_RESPONCE = 202,
	ID_AIM_SYNC = 203,
	ID_WEAPONS_UPDATE = 204,
	ID_STATS_UPDATE = 205,
	ID_BULLET_SYNC = 206,
	ID_PLAYER_SYNC = 207,
	ID_UNK_208_SYNC = 208, // TODO: ID_UNK_208_SYNC
	ID_UNOCCUPIED_SYNC = 209,
	ID_TRAILER_SYNC = 210,
	ID_PASSENGER_SYNC = 211,
	ID_SPECTATOR_SYNC = 212,
};

#endif
